### ISSUE TITLE
Bug Report: Client service crashes after player entry

### ISSUE THREAD

**Issue by cmradix** [ArchaicQuest/ArchaicQuest-II-Web-Client#48]
node:events:489
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (D:\project\aq2\ArchaicQuest-II-Web-Client\node_modules\memfs\lib\volume.js:2047:17)
    at FsReadStream._destroy (D:\project\aq2\ArchaicQuest-II-Web-Client\node_modules\memfs\lib\volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at class_1.destroy (node:internal/streams/destroy:71:5)
    at class_1.<anonymous> (D:\project\aq2\ArchaicQuest-II-Web-Client\node_modules\memfs\lib\volume.js:1962:22)
    at class_1.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on class_1 instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

The runtime environment clones the latest GITHUB code, using windows11 and Node.js v20.3.1, with the rest default.

**Comment by LiamKenneth** [comment]
Hi, do you have NVM installed? use that to install and use node v16 it works on that version. I need to update the projects to work with the latest node version

**Comment by cmradix** [comment]
> Hi, do you have NVM installed? use that to install and use node v16 it works on that version. I need to update the projects to work with the latest node version

No, I'll try. Thank you for your answer. Also for Admin, I encountered more serious errors under the new version of nodejs：
> archaic-quest-ii@0.0.0 start
> ng serve --port 1337

10% building 3/3 modules 0 active(node:7700) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
10% building 3/4 modules 1 active ...pack-dev-server\client\index.js?http://0.0.0.0:0/sockjs-node&sockPath=/sockjs-nodenode:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\loader-runner\lib\LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:47:13)
    at processResource (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\Compilation.js:739:10)
    at D:\project\aq2\ArchaicQuest-II-Web-Admin\node_modules\webpack\lib\Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

This issue can be mitigated by using $env:NODE_OPTIONS="--openssl-legacy-provider"

**Comment by LiamKenneth** [comment]
Yeah both need to be updated to the latest angular version but not yet had the chance to do it. Just been using v16 with both. Should be updated really the latest has some speed improvements.

Let me know if it works for you with NVM and running v16

**Comment by cmradix** [comment]
> Yeah both need to be updated to the latest angular version but not yet had the chance to do it. Just been using v16 with both. Should be updated really the latest has some speed improvements.
> 
> Let me know if it works for you with NVM and running v16

they work on nvm and v16.20.1, but not work on v18.17.0
